"""
Package for fitting the time-series of debuts and summarize the results.

See <data_preparation.py> for the generation of data used for fittings
See <cost_func.py> for the definition of cost function used for fittings
See <.../src/fitting.py> for the fitting procedures

<fit_res.py> repackage the fitting results generated by <.../src/fitting.py>
<fit_sum.py> summarizes the fitting results
"""
